export default function render() {
    return (
        <div>
            <Node
                y={20}
                x={500}
            />
            <Node
                y={120}
                x={250}
            />
            <Node
                y={120}
                x={750}
            />
            <Node
                y={220}
                x={125}
            />
            <Node
                y={220}
                x={375}
            />
            <Node
                y={220}
                x={625}
            />
            <Node
                y={220}
                x={875}
            />
            <Node
                y={320}
                x={63}
            />
            <Node
                y={320}
                x={188}
            />
            <Node
                y={320}
                x={313}
            />
            <Node
                y={320}
                x={438}
            />
            <Node
                y={320}
                x={563}
            />
            <Node
                y={320}
                x={688}
            />
            <Node
                y={320}
                x={816}
            />
            <Node
                y={320}
                x={938}
            />
        </div>
    )
}